name: Actions Workflow

on: 
  # pull_request:
  #   types: [closed, assigned, opened, reopened]
  schedule:
    - cron: "0/5 * * * *"
    - cron: "0/6 * * * *"

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{github.token}}"
          # git clone git@github.$GITHUB_REPOSITORY
          git checkout $ SG
      - name: Checkout
        uses: actions/checkout@v1
      - name: List Files
        run: |
          pwd
          ls -a
      - name: Simple-Js-Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greet: Flippie
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"         