name: JS Actions Workflow

on: [push]

jobs: 
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS Action
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Chris Mc
      - name: Log Greeting Time
        run: echo "${{
        steps.greet.output.Time
        }}"